steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/solver-service:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/solver-service:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'solver-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/solver-service:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8001'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8001'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/solver-service:$COMMIT_SHA' 