apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solver-service
  template:
    metadata:
      labels:
        app: solver-service
    spec:
      containers:
        - name: solver-service
          image: <your-solver-image>
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: solver-service
spec:
  type: ClusterIP
  selector:
    app: solver-service
  ports:
    - port: 8080
      targetPort: 8080 