apiVersion: v1
kind: Service
metadata:
  name: mcp-service
spec:
  type: ClusterIP
  selector:
    app: mcp-service
  ports:
    - port: {{ .Values.mcp.port }}
      targetPort: {{ .Values.mcp.port }} 