apiVersion: v1
kind: Service
metadata:
  name: solver-service
spec:
  type: ClusterIP
  selector:
    app: solver-service
  ports:
    - port: {{ .Values.solver.port }}
      targetPort: {{ .Values.solver.port }} 