apiVersion: v1
kind: Service
metadata:
  name: solver-service
  namespace: solver
spec:
  selector:
    app: solver-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP